defined url_defaults to an empty dict instead of None
jaykay9999/flaskreviewthree pull request #1
Opened 2024-02-08 02:50 UTC by jaykay99992

Changed 

`url_defaults: dict | None = None,`

to 

`url_defaults: dict | None = {},`

which makes url_defaults an empty dictionary from the beginning to avoid checking it later with:

```
        if url_defaults is None:
            url_defaults = {}
```

2024-02-15 20:11 UTC, JeremieBergeron requested changes

2024-02-15 20:11 UTC, JeremieBergeron commented on src/flask/sansio/blueprints.py
> +        url_defaults: dict | None = {},
Since you have replaced the default value from ``None`` with an ``empty dictionary``, you need to change the typing. 
Also, you set root_path with an empty dictionary, but it needs to be a string. There are many tests that are currently failing because of this change.
Additionally, we need maintain the current behavior when root_path is empt so you will need to update the class docstring.

2024-02-17 16:11 UTC, jaykay99992 commented on src/flask/sansio/blueprints.py
> +        url_defaults: dict | None = {},
@JeremieBergeron Just to clarify, do I just reject the proposed changes? or simply change root_path : str | None = None ?

2024-02-18 16:19 UTC, JeremieBergeron commented on src/flask/sansio/blueprints.py
> +        url_defaults: dict | None = {},
Reject the changes. Even if you correct the typing, there will still be many tests that fails.

2024-02-19 16:35 UTC, closed without merging

2024-02-19 16:35 UTC, jaykay9999 commented
Pull request rejected due to failing tests